# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, pipeline ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        path: [ '/home/runner/work/Jetpack-Compose-Theme-Configurator/Jetpack-Compose-Theme-Configurator/build/compose/binaries/main/deb/kotlinjvmcomposedesktopapplication_1.0.0-1_amd64.deb','/Users/runner/work/Jetpack-Compose-Theme-Configurator/Jetpack-Compose-Theme-Configurator/build/compose/binaries/main/dmg/KotlinJvmComposeDesktopApplication-1.0.0.dmg','D:\a\Jetpack-Compose-Theme-Configurator\Jetpack-Compose-Theme-Configurator\build\compose\binaries\main\msi\KotlinJvmComposeDesktopApplication-1.0.0.msi']
    name: (${{ matrix.os }}) desktop-configurator
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: ./gradlew package
      - uses: actions/upload-artifact@v2
        with:
          name: compose-configurator-desktop-application
          path: ${{ matrix.path }}

